### ISSUE TITLE
can not compile code on the master brunch

### ISSUE THREAD

**Issue by denisgav** [pulp-platform/riscv-isa-sim#2]
I have tried to compile master branch and I'm getting next error:

_../riscv/sim.h:10:10: fatal error: fesvr/htif.h: No such file or directory
 #include <fesvr/htif.h>
          ^~~~~~~~~~~~~~_

I checked that in original version of spike there is "fesvr" folder that contains classes for interaction with used in console.
Here is link to fesvr folder in original repository:
_https://github.com/riscv/riscv-isa-sim/tree/master/fesvr_

Please check that all necessary folders were copied from original repository and there is no compilation errors on the master branch.

**Comment by bluewww** [comment]
Should be fixed in master
